/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package industry_project;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sharma1
 */
public class billing extends javax.swing.JInternalFrame {

    /**
     * Creates new form billing
     */
    public billing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Bill");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Date");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 80, 70, 20);

        jLabel2.setBackground(new java.awt.Color(255, 255, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel2.setText("Bill");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 20, 70, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Dealer Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 120, 120, 27);

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(280, 80, 150, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(280, 120, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Net Total");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(610, 490, 100, 30);

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(710, 490, 130, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Product" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(280, 260, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setText("Select Product");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 260, 100, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1.setText("Claculate Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 490, 130, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton2.setText("Save Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(710, 540, 120, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Company", "Rate", "Current Quantity", "Quantity", "Total", "Remaining Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 300, 800, 180);

        jTextField4.setEditable(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(560, 80, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("Phone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 160, 100, 30);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(280, 160, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setText("Bill No.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 80, 70, 27);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel36.setText("Company");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(130, 210, 120, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Company" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(280, 210, 150, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose type" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(530, 210, 150, 30);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel39.setText("Type");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(450, 210, 50, 30);

        setBounds(0, 0, 877, 622);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed



        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";

        if (jComboBox1.getSelectedIndex() > 0) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection myconnection = DriverManager.getConnection(path + place, "root", "");
                String memberid, name, phone, ok;
                try {
                    String q = "select * from products where items=?";
                    PreparedStatement mystatement = myconnection.prepareStatement(q);
                    mystatement.setString(1, jComboBox1.getSelectedItem().toString());
                    DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                    ResultSet myresult = mystatement.executeQuery();

                    if (myresult.next()) {
                        do {
                            memberid = myresult.getString("items");
                            name = myresult.getString("category");
                            phone = myresult.getString("rates");
                            ok = myresult.getString("quantity");
                            mymodel.addRow(new Object[]{memberid, name, phone, ok});
                        } while (myresult.next());
                    }
                    mystatement.close();
                    myconnection.close();

                } catch (Exception ae) {
                    JOptionPane.showMessageDialog(rootPane, "Error in Query item " + ae.getMessage());
                }
            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
            }
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        java.util.Date obj = new java.util.Date();
        SimpleDateFormat myformat = new SimpleDateFormat("dd-MM-yyyy");
        String dateofbill = myformat.format(obj);
        jTextField4.setText(dateofbill);
        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "select * from products";
                PreparedStatement mystatement = myconnection.prepareStatement(q);


                ResultSet myresult = mystatement.executeQuery();

                if (myresult.next()) {

                    do {
                        jComboBox1.addItem(myresult.getString("items"));
                    } while (myresult.next());
                }

            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "No records exist");
            }
            try {
                String q = "select * from bill order by billid";
                PreparedStatement mystatement = myconnection.prepareStatement(q);


                ResultSet myresult = mystatement.executeQuery();

                if (myresult.next()) {
                    myresult.last();
                    int n = Integer.parseInt(myresult.getString(1));
                    n++;
                    jTextField1.setText("" + n);
                } else {
                    jTextField1.setText("1");
                }
                mystatement.close();


            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "error id fetch" + ae.getMessage());
            }

            try {
                String q = "select * from Company";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                ResultSet myresult = mystatement.executeQuery();
                if (myresult.next()) {
                    do {
                        jComboBox2.addItem(myresult.getString("company"));
                    } while (myresult.next());
                }
                mystatement.close();
                myconnection.close();

            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Error in query comp " + ae.getMessage());
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        int r = jTable1.getRowCount();
        double rate = 0, qty = 0, total = 0, net = 0, rem_qty = 0, cur_qty = 0;
        //    DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < r; i++) {
            rate = Double.parseDouble(jTable1.getValueAt(i, 2).toString());
            qty = Double.parseDouble(jTable1.getValueAt(i, 4).toString());
            cur_qty = Double.parseDouble(jTable1.getValueAt(i, 3).toString());
            total = rate * qty;
            jTable1.setValueAt("" + total, i, 5);
            net += total;
            rem_qty = cur_qty - qty;
            //      if(rem_qty<0)
            //    {
            //     jButton2.setVisible(false);
            //    JOptionPane.showMessageDialog(rootPane, "Error in Total");
            //  mymodel.setRowCount(0);


            //        }
            //      else if(rem_qty>0)
            //     {
            //       jButton2.setVisible(true);
            //  }
            jTable1.setValueAt("" + rem_qty, i, 6);
//if(total<0 && rem_qty<0)
            //      {
            //        jButton2.setVisible(false);
            //      JOptionPane.showMessageDialog(rootPane, "Error in Total");
            //}
        }

        jTextField3.setText(String.valueOf(net));






    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

//if(Integer.parseInt(jTextField3.getText())>0){

        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            String products = "", quantity = "";
            try {
                String q = "insert into bill values(?,?,?,?,?,?,?)";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, jTextField1.getText());
                mystatement.setString(2, jTextField2.getText());
                mystatement.setString(5, jTextField3.getText());
                java.util.Date obj = new java.util.Date();
                SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
                String dateofbill = myformat.format(obj);

                mystatement.setString(7, dateofbill);


                mystatement.setString(6, jFormattedTextField1.getText());


                int r = jTable1.getRowCount();
                for (int i = 0; i < r; i++) {
                    products += jTable1.getValueAt(i, 0) + ",";
                    quantity += jTable1.getValueAt(i, 4) + ",";
                }

                mystatement.setString(3, products);
                mystatement.setString(4, quantity);


                mystatement.execute();
                mystatement.close();
                JOptionPane.showMessageDialog(rootPane, "Bill Saved");

                this.dispose();
                billing obj2 = new billing();
                obj2.setVisible(true);
                frame1.jDesktopPane1.add(obj2);




            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "bill not saved" + ae.getMessage());
            }

            int r = jTable1.getRowCount();
            for (int i = 0; i < r; i++) {
                try {
                    String q = "update products set quantity=? where items=?";
                    PreparedStatement mystatement = myconnection.prepareStatement(q);
                    mystatement.setString(1, jTable1.getValueAt(i, 6).toString());
                    mystatement.setString(2, jTable1.getValueAt(i, 0).toString());


                    mystatement.executeUpdate();


                    mystatement.close();


                } catch (Exception ae) {
                    JOptionPane.showMessageDialog(rootPane, "Error in Query" + ae.getMessage());
                }
            }

            myconnection.close();
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
        }
//    }
//else 
//{
        //  JOptionPane.showMessageDialog(rootPane, "Error in Total");
//}



    }//GEN-LAST:event_jButton2ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
    String path = "jdbc:mysql://localhost/";
    String place = "factorydb";
    if (jComboBox2.getSelectedIndex() > 0) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");

            try {
                String q = "select subcategory from category where category1=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, jComboBox2.getSelectedItem().toString());
                ResultSet myresult = mystatement.executeQuery();
                jComboBox3.removeAllItems();
                if (myresult.next()) {
                    jComboBox3.addItem("Choose Type");
                    do {
                        jComboBox3.addItem(myresult.getString("subcategory"));
                    } while (myresult.next());
                }
                mystatement.close();
                myconnection.close();

            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Result not Found");
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
        }
    }// TODO add your handling code here:
}//GEN-LAST:event_jComboBox2ActionPerformed

private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed


    if (jComboBox3.getSelectedIndex() > 0) {
        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "select * from products where category=? and subcategory=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, jComboBox2.getSelectedItem().toString());
                mystatement.setString(2, jComboBox3.getSelectedItem().toString());
                ResultSet myresult = mystatement.executeQuery();


                jComboBox1.removeAllItems();
                if (myresult.next()) {
                    jComboBox1.addItem("Choose Product");
                    do {
                        jComboBox1.addItem(myresult.getString("items"));
                    } while (myresult.next());
                }
                mystatement.close();
                myconnection.close();

            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Error in query " + ae.getMessage());
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
        }

    }

}//GEN-LAST:event_jComboBox3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
