/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package industry_project;

import java.sql.*;
import javax.swing.JOptionPane;
public class Company extends javax.swing.JInternalFrame {

    /**
     * Creates new form Company
     */
    public Company() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        subcategory = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Add Company");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Add Company");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 20, 150, 30);

        subcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subcategoryActionPerformed(evt);
            }
        });
        getContentPane().add(subcategory);
        subcategory.setBounds(40, 70, 230, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 130, 110, 30);

        setBounds(0, 0, 314, 227);
    }// </editor-fold>//GEN-END:initComponents

    private void subcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subcategoryActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String path="jdbc:mysql://localhost/";
        String place="factorydb";
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection= DriverManager.getConnection(path+place,"root","");
            try
            {
                String q="insert into Company values(?)";
                PreparedStatement mystatement =myconnection.prepareStatement(q);
                mystatement.setString(1, subcategory.getText());
                mystatement.execute();
                JOptionPane.showMessageDialog(rootPane, "Saved Successfully");
                subcategory.setText(null);

                mystatement.close();
                myconnection.close();

            }
            catch(Exception ae)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in Query" + ae.getMessage());
            }
        }
        catch(Exception ae)
        {
            JOptionPane.showMessageDialog(rootPane,"Error in connection" + ae.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField subcategory;
    // End of variables declaration//GEN-END:variables
}
