/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package industry_project;

import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sharma1
 */
public class editpage extends javax.swing.JInternalFrame {

    /**
     * Creates new form menu
     */
    public editpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        postbox = new javax.swing.JComboBox();
        phonebox = new javax.swing.JFormattedTextField();
        box1 = new javax.swing.JRadioButton();
        box2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressbox = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        idbox = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Edit Employee");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Address");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 320, 80, 30);

        jLabel3.setText("Phone no.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 180, 60, 30);

        jLabel4.setText("Post");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 130, 60, 30);

        jLabel5.setText("ID No.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 30, 70, 30);

        jLabel6.setText("Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 80, 80, 30);
        getContentPane().add(namebox);
        namebox.setBounds(350, 80, 200, 30);

        postbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Post", "Manager", "SuperVisor", "Foreman", "Workers", "Helper", "Security Guard" }));
        postbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postboxActionPerformed(evt);
            }
        });
        getContentPane().add(postbox);
        postbox.setBounds(350, 130, 200, 30);

        try {
            phonebox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(phonebox);
        phonebox.setBounds(350, 180, 200, 30);

        buttonGroup1.add(box1);
        box1.setText("Male");
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });
        getContentPane().add(box1);
        box1.setBounds(350, 230, 80, 23);

        buttonGroup1.add(box2);
        box2.setText("Female");
        getContentPane().add(box2);
        box2.setBounds(440, 230, 110, 23);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        addressbox.setColumns(20);
        addressbox.setRows(5);
        jScrollPane1.setViewportView(addressbox);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(350, 320, 200, 110);

        jLabel8.setText("Gender");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 220, 70, 30);

        jLabel2.setText("D.O.B");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 260, 70, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(350, 270, 60, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(410, 270, 70, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(480, 270, 70, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 80, 110, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(580, 380, 110, 31);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone", "Gender", "Address", "D.O.B", "Post"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 440, 860, 180);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(590, 30, 110, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(720, 380, 110, 31);
        getContentPane().add(idbox);
        idbox.setBounds(350, 30, 200, 30);

        setBounds(0, 0, 918, 661);
    }// </editor-fold>//GEN-END:initComponents

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box1ActionPerformed
    
    private void postboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postboxActionPerformed
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
    }//GEN-LAST:event_formInternalFrameActivated
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        idbox.setText("");
        phonebox.setText("");
        addressbox.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        postbox.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        
        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            String memberid, name, phone, address, dob, gender, post;
            try {
                String q = "select * from member where NAME like '%" + namebox.getText() + "%'";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                ResultSet myresult = mystatement.executeQuery();
                mymodel.setRowCount(0);
                jScrollPane3.setVisible(true);
                if (myresult.next()) {
                    do {
                        memberid = myresult.getString("ID");
                        name = myresult.getString("NAME");
                        phone = myresult.getString("PHONE");
                        address = myresult.getString("ADDRESS");
                        dob = myresult.getString("dob");
                        gender = myresult.getString("GENDER");
                        post = myresult.getString("usertype");
                        mymodel.addRow(new Object[]{memberid, name, phone, gender, address, dob, post});
                        jScrollPane3.setVisible(true);
                    } while (myresult.next());
                } else {
                    jScrollPane3.setVisible(false);
                    JOptionPane.showMessageDialog(rootPane, "No records exist");
                }
                mystatement.close();
                myconnection.close();
                
            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Member not Found");
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";
        int i = JOptionPane.showConfirmDialog(rootPane, "Are u sure want to update this employee");
        if (i == 0) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection myconnection = DriverManager.getConnection(path + place, "root", "");
                try {
                    String q = "update member set NAME=?,PHONE=?,ADDRESS=?,GENDER=?,dob=?,usertype=? where ID=?";
                    PreparedStatement mystatement = myconnection.prepareStatement(q);
                    mystatement.setString(1, namebox.getText());
                    mystatement.setString(2, phonebox.getText());
                    if (box1.isSelected()) {
                        mystatement.setString(4, "Male");
                    } else if (box2.isSelected()) {
                        mystatement.setString(4, "Female");
                    }
                    mystatement.setString(3, addressbox.getText());
                    String dob = jComboBox3.getSelectedItem() + "-" + jComboBox2.getSelectedItem() + "-" + jComboBox1.getSelectedItem();
                    mystatement.setString(5, dob);
                    mystatement.setString(6, postbox.getSelectedItem().toString());
                    mystatement.setString(7, idbox.getText());
                    mystatement.execute();
                    JOptionPane.showMessageDialog(rootPane, "Update Successfully");
                    
                    
                    
                    mystatement.close();
                    myconnection.close();
                    
                    namebox.setText("");
                    jButton2ActionPerformed(null);
                    
                } catch (Exception ae) {
                    JOptionPane.showMessageDialog(rootPane, "Error in Query" + ae.getMessage());
                }
            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int myrow = jTable1.getSelectedRow();
        
        String data = (String) jTable1.getValueAt(myrow, 0);
        idbox.setText(data);
        jButton4ActionPerformed(null);
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        jScrollPane3.setVisible(false);
        
        
        for (int a = 1; a <= 31; a++) {
            if (a < 10) {
                jComboBox1.addItem("0" + a);
            } else {
                jComboBox1.addItem("" + a);
            }
            
        }
        for (int a = 1; a <= 12; a++) {
            if (a < 10) {
                jComboBox2.addItem("0" + a);
            } else {
                jComboBox2.addItem("" + a);
            }
            
        }
        for (int a = 1975; a <= 2013; a++) {
            jComboBox3.addItem("" + a);
        }
        
    }//GEN-LAST:event_formInternalFrameOpened
    
private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    String path = "jdbc:mysql://localhost/";
    String place = "factorydb";
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection myconnection = DriverManager.getConnection(path + place, "root", "");
        try {
            String q = "select * from member where ID=?";
            PreparedStatement mystatement = myconnection.prepareStatement(q);
            mystatement.setString(1, idbox.getText());
            ResultSet myresult = mystatement.executeQuery();
            if (myresult.next()) {
                namebox.setText(myresult.getString("NAME"));
                phonebox.setText(myresult.getString("PHONE"));
                addressbox.setText(myresult.getString("ADDRESS"));
                String db = myresult.getString("dob");
                String a[] = db.split("-");
                jComboBox1.setSelectedItem(a[2]);
                jComboBox2.setSelectedItem(a[1]);
                jComboBox3.setSelectedItem(a[0]);
                if (myresult.getString("GENDER").equals("Male")) {
                    box1.setSelected(true);
                } else if (myresult.getString("GENDER").equals("Female")) {
                    box2.setSelected(true);
                }
                
                String p = myresult.getString("usertype");
                postbox.setSelectedItem(p);
            } else {
                JOptionPane.showMessageDialog(rootPane, "NO record Found", "Error", 0);
            }
            mystatement.close();
            myconnection.close();
            
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in Query" + ae.getMessage());
        }
    } catch (Exception ae) {
        JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
    }
}//GEN-LAST:event_jButton4ActionPerformed
    
private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    String path = "jdbc:mysql://localhost/";
    String place = "factorydb";
    
    int i = JOptionPane.showConfirmDialog(rootPane, "Are u sure want to delete this employee");
    if (i == 0) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "delete from member where ID=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, idbox.getText());
                int b = mystatement.executeUpdate();
                if (b > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Deleted Successfully");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Already deleted");
                }
                mystatement.close();
                myconnection.close();
                
            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query" + ae.getMessage());
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
        }
    }
}//GEN-LAST:event_jButton5ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressbox;
    private javax.swing.JRadioButton box1;
    private javax.swing.JRadioButton box2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField idbox;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField namebox;
    private javax.swing.JFormattedTextField phonebox;
    private javax.swing.JComboBox postbox;
    // End of variables declaration//GEN-END:variables
}
