/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package industry_project;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sharma1
 */
public class editmanager extends javax.swing.JInternalFrame {

    /**
     * Creates new form manager
     */
    public editmanager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usernamebox = new javax.swing.JTextField();
        namebox = new javax.swing.JTextField();
        passwordbox = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        postbox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        usernamebox1 = new javax.swing.JTextField();
        namebox1 = new javax.swing.JTextField();
        passwordbox1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        postbox1 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        usernamebox2 = new javax.swing.JTextField();
        namebox2 = new javax.swing.JTextField();
        passwordbox2 = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        postbox2 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        usernamebox3 = new javax.swing.JTextField();
        namebox3 = new javax.swing.JTextField();
        passwordbox3 = new javax.swing.JPasswordField();
        jButton7 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        postbox3 = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Edit Manager");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 220, 80, 30);

        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 180, 80, 30);

        jLabel4.setText("Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 80, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setText("Edit Manager Account");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 20, 240, 30);

        usernamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameboxActionPerformed(evt);
            }
        });
        getContentPane().add(usernamebox);
        usernamebox.setBounds(110, 180, 150, 30);

        namebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameboxActionPerformed(evt);
            }
        });
        getContentPane().add(namebox);
        namebox.setBounds(110, 80, 150, 30);

        passwordbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordboxActionPerformed(evt);
            }
        });
        getContentPane().add(passwordbox);
        passwordbox.setBounds(110, 220, 150, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 270, 100, 30);

        jLabel2.setText("User Type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 130, 60, 30);

        postbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Post", "Admin", "Manager" }));
        postbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postboxActionPerformed(evt);
            }
        });
        getContentPane().add(postbox);
        postbox.setBounds(110, 130, 150, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 80, 110, 25);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("Edit Manager");
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel5.setText("Password");
        jInternalFrame1.getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 220, 80, 30);

        jLabel7.setText("Username");
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 80, 80, 30);

        jLabel8.setText("Name");
        jInternalFrame1.getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 180, 80, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel9.setText("Edit Manager Account");
        jInternalFrame1.getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 20, 240, 30);

        usernamebox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamebox1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(usernamebox1);
        usernamebox1.setBounds(410, 80, 110, 30);

        namebox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namebox1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(namebox1);
        namebox1.setBounds(410, 180, 110, 30);

        passwordbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordbox1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(passwordbox1);
        passwordbox1.setBounds(410, 220, 110, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton3.setText("Create Account");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(330, 310, 150, 30);

        jLabel10.setText("User Type");
        jInternalFrame1.getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 130, 60, 30);

        postbox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Post", "Admin", "Manager" }));
        postbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postbox1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(postbox1);
        postbox1.setBounds(410, 130, 110, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton4);
        jButton4.setBounds(550, 80, 110, 25);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 0, 85, 33);

        jInternalFrame2.setClosable(true);
        jInternalFrame2.setMaximizable(true);
        jInternalFrame2.setResizable(true);
        jInternalFrame2.setTitle("Edit Manager");
        jInternalFrame2.getContentPane().setLayout(null);

        jLabel11.setText("Password");
        jInternalFrame2.getContentPane().add(jLabel11);
        jLabel11.setBounds(300, 220, 80, 30);

        jLabel12.setText("Username");
        jInternalFrame2.getContentPane().add(jLabel12);
        jLabel12.setBounds(300, 80, 80, 30);

        jLabel13.setText("Name");
        jInternalFrame2.getContentPane().add(jLabel13);
        jLabel13.setBounds(300, 180, 80, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel14.setText("Edit Manager Account");
        jInternalFrame2.getContentPane().add(jLabel14);
        jLabel14.setBounds(320, 20, 240, 30);

        usernamebox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamebox2ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(usernamebox2);
        usernamebox2.setBounds(410, 80, 110, 30);

        namebox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namebox2ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(namebox2);
        namebox2.setBounds(410, 180, 110, 30);

        passwordbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordbox2ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(passwordbox2);
        passwordbox2.setBounds(410, 220, 110, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton5.setText("Create Account");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton5);
        jButton5.setBounds(330, 310, 150, 30);

        jLabel15.setText("User Type");
        jInternalFrame2.getContentPane().add(jLabel15);
        jLabel15.setBounds(300, 130, 60, 30);

        postbox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Post", "Admin", "Manager" }));
        postbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postbox2ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(postbox2);
        postbox2.setBounds(410, 130, 110, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton6);
        jButton6.setBounds(550, 80, 110, 25);

        jInternalFrame3.setClosable(true);
        jInternalFrame3.setMaximizable(true);
        jInternalFrame3.setResizable(true);
        jInternalFrame3.setTitle("Edit Manager");
        jInternalFrame3.getContentPane().setLayout(null);

        jLabel16.setText("Password");
        jInternalFrame3.getContentPane().add(jLabel16);
        jLabel16.setBounds(300, 220, 80, 30);

        jLabel17.setText("Username");
        jInternalFrame3.getContentPane().add(jLabel17);
        jLabel17.setBounds(300, 80, 80, 30);

        jLabel18.setText("Name");
        jInternalFrame3.getContentPane().add(jLabel18);
        jLabel18.setBounds(300, 180, 80, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel19.setText("Edit Manager Account");
        jInternalFrame3.getContentPane().add(jLabel19);
        jLabel19.setBounds(320, 20, 240, 30);

        usernamebox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamebox3ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(usernamebox3);
        usernamebox3.setBounds(410, 80, 110, 30);

        namebox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namebox3ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(namebox3);
        namebox3.setBounds(410, 180, 110, 30);

        passwordbox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordbox3ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(passwordbox3);
        passwordbox3.setBounds(410, 220, 110, 30);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton7.setText("Create Account");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(jButton7);
        jButton7.setBounds(330, 310, 150, 30);

        jLabel20.setText("User Type");
        jInternalFrame3.getContentPane().add(jLabel20);
        jLabel20.setBounds(300, 130, 60, 30);

        postbox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Post", "Admin", "Manager" }));
        postbox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postbox3ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(postbox3);
        postbox3.setBounds(410, 130, 110, 30);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jInternalFrame3.getContentPane().add(jButton8);
        jButton8.setBounds(550, 80, 110, 25);

        jInternalFrame2.getContentPane().add(jInternalFrame3);
        jInternalFrame3.setBounds(0, 0, 85, 33);

        getContentPane().add(jInternalFrame2);
        jInternalFrame2.setBounds(0, 0, 85, 33);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "User Type", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(290, 130, 260, 230);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(130, 310, 100, 30);

        setBounds(0, 0, 598, 422);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameboxActionPerformed
    
    private void nameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameboxActionPerformed
    
    private void passwordboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordboxActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";
        int i = JOptionPane.showConfirmDialog(rootPane, "Are u sure want to update this employee");
        if (i == 0) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection myconnection = DriverManager.getConnection(path + place, "root", "");
                try {
                    String q = "update createuser set  password=?,username=?,usertype=?, name1=? where username=? ";
                    PreparedStatement mystatement = myconnection.prepareStatement(q);
                    mystatement.setString(1, passwordbox.getText());
                    mystatement.setString(2, usernamebox.getText());
                    mystatement.setString(3, postbox.getSelectedItem().toString());
                    mystatement.setString(4, namebox.getText());
                    mystatement.setString(5, data);
                    
                    int x = mystatement.executeUpdate();
                    if (x > 0) {
                        JOptionPane.showMessageDialog(rootPane, "Update Successfully");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Update unSuccessfully");
                        
                    }
                    
                    namebox.setText("");
                    jButton2ActionPerformed(null);
                    mystatement.close();
                    myconnection.close();
                    
                    
                } catch (Exception ae) {
                    JOptionPane.showMessageDialog(rootPane, "Error in Query" + ae.getMessage());
                }
            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void postboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postboxActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        usernamebox.setText("");
        passwordbox.setText("");
        postbox.setSelectedIndex(0);
        
        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            String name, usertype, username;
            try {
                String q = "select * from createuser where name1 like '%" + namebox.getText() + "%'";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                ResultSet myresult = mystatement.executeQuery();
                mymodel.setRowCount(0);
                jScrollPane3.setVisible(true);
                if (myresult.next()) {
                    do {
                        name = myresult.getString("name1");
                        usertype = myresult.getString("usertype");
                        username = myresult.getString("username");
                        mymodel.addRow(new Object[]{name, usertype, username});
                        jScrollPane3.setVisible(true);
                    } while (myresult.next());
                } else {
                    jScrollPane3.setVisible(false);
                    JOptionPane.showMessageDialog(rootPane, "No records exist");
                    
                }
                while (myresult.next());
                
                mystatement.close();
                myconnection.close();
                
            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Member not Found");
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void usernamebox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamebox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamebox1ActionPerformed
    
    private void namebox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namebox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namebox1ActionPerformed
    
    private void passwordbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordbox1ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void postbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postbox1ActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void usernamebox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamebox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamebox2ActionPerformed
    
    private void namebox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namebox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namebox2ActionPerformed
    
    private void passwordbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordbox2ActionPerformed
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void postbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postbox2ActionPerformed
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void usernamebox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamebox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamebox3ActionPerformed
    
    private void namebox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namebox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namebox3ActionPerformed
    
    private void passwordbox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordbox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordbox3ActionPerformed
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private void postbox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postbox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postbox3ActionPerformed
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed
    String data = "";
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int myrow = jTable1.getSelectedRow();
        
        data = (String) jTable1.getValueAt(myrow, 2);
        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            
            try {
                String q = "select * from createuser where username=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, data);
                DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                ResultSet myresult = mystatement.executeQuery();
                mymodel.setRowCount(0);
                jScrollPane3.setVisible(true);
                if (myresult.next()) {
                    
                    namebox.setText(myresult.getString("name1"));
                    String p = myresult.getString("usertype");
                    postbox.setSelectedItem(p);
                    usernamebox.setText(myresult.getString("username"));
                    passwordbox.setText(myresult.getString("password"));
                }
                mystatement.close();
                myconnection.close();
                
            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Result not Found");
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
        }
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        jScrollPane3.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened
    
private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    
    String path = "jdbc:mysql://localhost/";
    String place = "factorydb";
    
    int i = JOptionPane.showConfirmDialog(rootPane, "Are u sure want to delete this Account ? ");
    if (i == 0) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "delete from createuser where username=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, usernamebox.getText());
                int b = mystatement.executeUpdate();
                if (b > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Deleted Successfully");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Already deleted");
                }
                mystatement.close();
                myconnection.close();
                
            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Error in Query" + ae.getMessage());
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
        }
    }
    
}//GEN-LAST:event_jButton9ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField namebox1;
    private javax.swing.JTextField namebox2;
    private javax.swing.JTextField namebox3;
    private javax.swing.JPasswordField passwordbox;
    private javax.swing.JPasswordField passwordbox1;
    private javax.swing.JPasswordField passwordbox2;
    private javax.swing.JPasswordField passwordbox3;
    private javax.swing.JComboBox postbox;
    private javax.swing.JComboBox postbox1;
    private javax.swing.JComboBox postbox2;
    private javax.swing.JComboBox postbox3;
    private javax.swing.JTextField usernamebox;
    private javax.swing.JTextField usernamebox1;
    private javax.swing.JTextField usernamebox2;
    private javax.swing.JTextField usernamebox3;
    // End of variables declaration//GEN-END:variables
}
