/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package industry_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sharma1
 */
public class productsrate extends javax.swing.JInternalFrame {

    /**
     * Creates new form productsrate
     */
    public productsrate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itembox = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        ratebox1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        ratebox2 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Products rates");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        itembox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemboxActionPerformed(evt);
            }
        });
        getContentPane().add(itembox);
        itembox.setBounds(140, 30, 150, 30);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel36.setText("Company");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(20, 70, 120, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 160, 100, 30);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel38.setText("Item");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(30, 30, 80, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Company" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(140, 70, 150, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose type" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(390, 70, 150, 30);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel40.setText("Rates/Piece");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(20, 110, 120, 30);

        ratebox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratebox1ActionPerformed(evt);
            }
        });
        getContentPane().add(ratebox1);
        ratebox1.setBounds(140, 110, 150, 30);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel41.setText("Quantity");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(310, 110, 80, 30);

        ratebox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratebox2ActionPerformed(evt);
            }
        });
        getContentPane().add(ratebox2);
        ratebox2.setBounds(390, 110, 150, 30);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel39.setText("Type");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(310, 70, 50, 30);

        setBounds(0, 0, 593, 254);
    }// </editor-fold>//GEN-END:initComponents

    private void itemboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String path="jdbc:mysql://localhost/";
       String place="factorydb";
       try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection myconnection= DriverManager.getConnection(path+place,"root","");
           try
           {
               String q="insert into products values(?,?,?,?,?)";
               PreparedStatement mystatement =myconnection.prepareStatement(q);
               
               
               mystatement.setString(1, itembox.getText());
               mystatement.setString(3, jComboBox1.getSelectedItem().toString());
               mystatement.setString(4, jComboBox2.getSelectedItem().toString());
               mystatement.setString(2, ratebox1.getText());
               mystatement.setString(5, ratebox2.getText());
               
               
               mystatement.execute();
           //    label.setText("Saved Succesfully");
              JOptionPane.showMessageDialog(rootPane, "Saved Successfully");
              itembox.setText(null);
              ratebox1.setText(null);
              ratebox2.setText(null);
              
               mystatement.close();
               myconnection.close();
               
           }
           catch(Exception ae)
           {
             JOptionPane.showMessageDialog(rootPane,"Error in Query" + ae.getMessage());
           }
       }
       catch(Exception ae)
               {
                 JOptionPane.showMessageDialog(rootPane,"Error in connection" + ae.getMessage());  
               }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
String path="jdbc:mysql://localhost/";
       String place="factorydb";
       try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection myconnection= DriverManager.getConnection(path+place,"root","");
           
           try
           {
               String q="select subcategory from category where category1=?";
               PreparedStatement mystatement =myconnection.prepareStatement(q);
               mystatement.setString(1, jComboBox1.getSelectedItem().toString());
               ResultSet myresult=mystatement.executeQuery();
               jComboBox2.removeAllItems();
               if(myresult.next())
               {
                   jComboBox2.addItem("Choose Size");
                   do
                   {
                       jComboBox2.addItem(myresult.getString("subcategory"));
                   }
                   while(myresult.next());
               }
                mystatement.close();
               myconnection.close();
               
           }
           catch(Exception ae)
           {
             JOptionPane.showMessageDialog(rootPane,"Result not Found");
           }
       }
       catch(Exception ae)
               {
                 JOptionPane.showMessageDialog(rootPane,"Error in connection" + ae.getMessage());  
               }          // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
 String path="jdbc:mysql://localhost/";
       String place="factorydb";
       try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection myconnection= DriverManager.getConnection(path+place,"root","");
           try
           {
               String q="select * from Company";
               PreparedStatement mystatement =myconnection.prepareStatement(q);
               ResultSet myresult=mystatement.executeQuery();
               if(myresult.next())
               {
                do
                {
                    jComboBox1.addItem(myresult.getString("company"));
                }
                while(myresult.next());
               }
                mystatement.close();
               myconnection.close();
               
           }
           catch(Exception ae)
           {
             JOptionPane.showMessageDialog(rootPane,"No records exist");
           }
       }
       catch(Exception ae)
               {
                 JOptionPane.showMessageDialog(rootPane,"Error in connection" + ae.getMessage());  
               }        
          
    }//GEN-LAST:event_formInternalFrameActivated

    private void ratebox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratebox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratebox1ActionPerformed

    private void ratebox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratebox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratebox2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField itembox;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JTextField ratebox1;
    private javax.swing.JTextField ratebox2;
    // End of variables declaration//GEN-END:variables
}
