/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package industry_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sharma1
 */
public class updateproducts extends javax.swing.JInternalFrame {

    /**
     * Creates new form productsrate
     */
    public updateproducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itembox = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ratebox = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();
        ratebox2 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Products rates");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        itembox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemboxActionPerformed(evt);
            }
        });
        getContentPane().add(itembox);
        itembox.setBounds(30, 100, 140, 30);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel36.setText("Update Products");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(330, 10, 160, 30);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel37.setText("Rates/Piece");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(550, 60, 120, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 150, 90, 30);

        ratebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateboxActionPerformed(evt);
            }
        });
        getContentPane().add(ratebox);
        ratebox.setBounds(530, 100, 90, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Category" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(180, 100, 150, 30);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel39.setText("Size");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(410, 60, 50, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose SubCategory", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(340, 100, 160, 30);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel40.setText("Item");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(80, 60, 80, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 150, 110, 30);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel38.setText("Company");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(200, 60, 120, 30);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Items", "Category", "Size", "Rates/Piece", "Quantity"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 750, 180);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel41.setText("Quantity");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(680, 60, 120, 30);

        ratebox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratebox2ActionPerformed(evt);
            }
        });
        getContentPane().add(ratebox2);
        ratebox2.setBounds(660, 100, 100, 30);

        setBounds(0, 0, 804, 454);
    }// </editor-fold>//GEN-END:initComponents

    private void itemboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed




        ratebox.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        ratebox2.setText("");


        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            String item, category, subcategory, rates, quantity;
            try {
                String q = "select * from products where items like '%" + itembox.getText() + "%'";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                ResultSet myresult = mystatement.executeQuery();
                mymodel.setRowCount(0);
                jScrollPane1.setVisible(true);
                if (myresult.next()) {
                    do {
                        item = myresult.getString("items");
                        category = myresult.getString("category");
                        subcategory = myresult.getString("subcategory");
                        rates = myresult.getString("rates");
                        quantity = myresult.getString("quantity");
                        mymodel.addRow(new Object[]{item, category, subcategory, rates, quantity});
                        jScrollPane1.setVisible(true);
                    } while (myresult.next());
                } else {
                    jScrollPane1.setVisible(false);
                    JOptionPane.showMessageDialog(rootPane, "No records exist");
                }
                mystatement.close();
                myconnection.close();

            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "No records exist");
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
        }
       }//GEN-LAST:event_jButton1ActionPerformed

    private void rateboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateboxActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";
        if (jComboBox1.getSelectedIndex() > 0) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection myconnection = DriverManager.getConnection(path + place, "root", "");

                try {
                    String q = "select subcategory from category where category1=?";
                    PreparedStatement mystatement = myconnection.prepareStatement(q);
                    mystatement.setString(1, jComboBox1.getSelectedItem().toString());
                    ResultSet myresult = mystatement.executeQuery();
                    jComboBox2.removeAllItems();
                    if (myresult.next()) {
                        jComboBox2.addItem("Choose Type");
                        do {
                            jComboBox2.addItem(myresult.getString("subcategory"));
                        } while (myresult.next());
                    }
                    mystatement.close();
                    myconnection.close();

                } catch (Exception ae) {
                    JOptionPane.showMessageDialog(rootPane, "Result not Found");
                }
            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
            }
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "select * from Company";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                ResultSet myresult = mystatement.executeQuery();
                if (myresult.next()) {
                    do {
                        jComboBox1.addItem(myresult.getString("company"));
                    } while (myresult.next());
                }
                jScrollPane1.setVisible(false);
                mystatement.close();
                myconnection.close();

            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "No records exist");
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
        }

    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";
        int i = JOptionPane.showConfirmDialog(rootPane, "Are u sure want to update this item");
        if (i == 0) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection myconnection = DriverManager.getConnection(path + place, "root", "");
                try {
                    String q = "update products set rates=?,category=?,subcategory=?,quantity=? where items=?";
                    PreparedStatement mystatement = myconnection.prepareStatement(q);
                    mystatement.setString(1, ratebox.getText());
                    mystatement.setString(2, jComboBox1.getSelectedItem().toString());
                    mystatement.setString(3, jComboBox2.getSelectedItem().toString());
                    mystatement.setString(4, ratebox2.getText());
                    mystatement.setString(5, itembox.getText());
                    mystatement.execute();

                    JOptionPane.showMessageDialog(rootPane, "Update Successfully");

                    itembox.setText("");
                    jButton1ActionPerformed(null);
                    mystatement.close();

                    myconnection.close();
                } catch (Exception ae) {
                    JOptionPane.showMessageDialog(rootPane, "Error in Query" + ae.getMessage());
                }
            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
            }
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            String item, category, subcategory, rates, quantity;
            try {
                String q = "select * from products where items like '%" + itembox.getText() + "%'";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                mymodel.fireTableDataChanged();
                ResultSet myresult = mystatement.executeQuery();
                mymodel.setRowCount(0);
                if (myresult.next()) {
                    do {
                        item = myresult.getString("items");
                        category = myresult.getString("category");
                        subcategory = myresult.getString("subcategory");
                        rates = myresult.getString("rates");
                        quantity = myresult.getString("quantity");
                        mymodel.addRow(new Object[]{item, category, subcategory, rates, quantity});
                    } while (myresult.next());
                }
                mystatement.close();
                myconnection.close();

            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "No records exist");
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int myrow = jTable1.getSelectedRow();

        String data = (String) jTable1.getValueAt(myrow, 0);
        String path = "jdbc:mysql://localhost/";
        String place = "factorydb";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "select * from products where items=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, data);
                ResultSet myresult = mystatement.executeQuery();
                if (myresult.next()) {
                    itembox.setText(myresult.getString("items"));
                    ratebox.setText(myresult.getString("rates"));
                    jComboBox1.setSelectedItem(myresult.getString("category"));
                    jComboBox2.setSelectedItem(myresult.getString("subcategory"));
                    ratebox2.setText(myresult.getString("quantity"));
                }
                mystatement.close();
                myconnection.close();

            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Error in query " + ae.getMessage());
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error in connection" + ae.getMessage());
        }


    }//GEN-LAST:event_jTable1MouseClicked

    private void ratebox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratebox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratebox2ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        jScrollPane1.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField itembox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ratebox;
    private javax.swing.JTextField ratebox2;
    // End of variables declaration//GEN-END:variables
}
